version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../WB_blog/.env
  
  backend:
    build: ../WB_blog
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../WB_blog/.env